# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/testing_nbdev',
                'doc_host': 'https://franfram.github.io',
                'git_url': 'https://github.com/franfram/testing_nbdev',
                'lib_path': 'testing_nbdev'},
  'syms': {'testing_nbdev.core': {'testing_nbdev.core.foo': ('core.html#foo', 'testing_nbdev/core.py')}}}
